name = "ResourceBundles"
uuid = "a9a2f26c-b040-4a74-98fd-7b69a57a6ccd"
authors = ["Klaus Crusius <klausC@users.noreply.github.com> and contributors"]
version = "0.2.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
julia = "1"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Logging"]
